// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VIGOR.Web.Data;

#nullable disable

namespace VIGOR.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521000000_AddAuditEvent")]
    partial class AddAuditEvent
    {
    }
}
