// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VIGOR.Web.Data;

#nullable disable

namespace VIGOR.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525030000_AddWorkPhone")]
    public partial class AddWorkPhone
    {
    }
}
